module:
  enabled: show-it

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 9uGp@iRB8g3VsQU
    listener:
      simple:
        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual
#        retry:
#          enabled: true
#          initial-interval: 3s
#          max-interval: 10s
#          max-attempts: 5
#          multiplier: 2

#      direct:
#        acknowledge-mode: manual
